title: Secuirty
#panel: true
visible: 
      - user: 5c4082cf03ff4a4e943c4b4d7309044f #lee
icon: mdi:security
id: VWsecuirty
cards:
    # The filter card will filter entities for their state
    - id: Secuirty
      type: vertical-stack
      title: Security Control
      cards:
            - type: glance
              
              entities:
                - input_select.alarm_mode
                - input_select.auto_mode
            - type: entities
              title: Motion
              show_header_toggle: false
              entities:
                - entity: binary_sensor.motion_sensor_158d00016d5813
                  name: Kitchen
                  secondary_info: last-changed 
                - entity: binary_sensor.motion_sensor_158d0001231c9b
                  name: Garage
                  secondary_info: last-changed 
                - entity: binary_sensor.motion_sensor_158d00016be379
                  name: Study
                  secondary_info: last-changed 
                - entity: binary_sensor.motion_sensor_158d00015da5fd
                  name: Theater
                  secondary_info: last-changed 
                - entity: binary_sensor.motion_sensor_158d00015a8b14
                  name: Dinning Area
                  secondary_info: last-changed  
                - entity: binary_sensor.motion_sensor_158d0001db087a
                  name: Activity
                  secondary_info: last-changed                   
                - entity:  binary_sensor.motion_sensor_158d0001db52e8
                  name: Patio
                  secondary_info: last-changed  
                - entity:   binary_sensor.motion_sensor_158d000171cc81
                  name: Porch
                  secondary_info: last-changed 
                - entity: binary_sensor.door_window_sensor_158d00014d20b8
                  name: Front door
                  secondary_info: last-changed 
                - entity: binary_sensor.door_window_sensor_158d0001d682cc
                  secondary_info: last-changed 
                  name: Laundry door
    

                 

              #show_state: false
            