- id: IFTTT garage door
  alias: IFTTT garage door
  trigger:
  - platform: event
    event_data:
      action: call_service
    event_type: ifttt_webhook_received
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
- id: theme-setup
  alias: Set theme at startup
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: Google Dark Theme
- id: '1602231034971'
  alias: Tag e1acae59-e38b-422d-b899-6180ee5306ce is scanned
  description: Test Tag
  trigger:
  - platform: tag
    tag_id: e1acae59-e38b-422d-b899-6180ee5306ce
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.kitchen_lights
  mode: single
- id: '1606117098955'
  alias: ANDROID - Close garage
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: CLOSE_GARAGE
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.garage_door_control
  - service: notify.mobile_app_pixel_5
    data:
      title: Garage Closed
      message: 'Garage door now closing '
  mode: single
- id: '1606444835621'
  alias: Tag Open Garage is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 7b8bd091-c850-4baa-9e45-417109181614
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.garage_door_control
  mode: single
- id: '1606447002311'
  alias: Tag Open Garage Door Iphone is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 02078992-b81a-478a-9880-5b0f0a529f0d
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.garage_door_control
  mode: single
- id: '1612575255576'
  alias: someone at front door
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: b5ad1235dc7b4fb9b97ebea910177072
    entity_id: binary_sensor.motion_sensor_158d000171cc81
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d00014d20b8
    state: closed
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.nesthub9608
      message: Someone is at the door
    entity_id: media_player.family_room_speaker
  mode: single
