homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HomeLat
  longitude: !secret HomeLong
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:
lovelace:
  mode: yaml
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

http:
  api_password: !secret http_password

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# recorder
recorder:
  purge_keep_days: 7
  purge_interval: 3
  db_url: !secret dbURL

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml

wemo:


mqtt:
  broker: 10.0.0.180
  port: 1883
  client_id: home-assistant-1
  username: !secret MQuser
  password: !secret MQpass


tuya:
  username: leeiberry@gmail.com
  password: light8944
  country_code: 61

input_select:
  alarm_mode:
    name: Alarm Mode
    options:
      - "off"
      - "on"
    icon: mdi:alarm-light


xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac:
      key: fyi1nxb0z1zwfs4u


device_tracker:
  - platform: nmap_tracker
    hosts:   -Pn 10.0.0.100-222
     # Minutes nmap will not scan a device, assuming it is home#    home_interval: 10
    # Seconds between each scan for new devices (default: 12)
    interval_seconds: 60
    # Seconds to wait till marking someone as not home after not being seen (default: 180)
    consider_home: 240
    track_new_devices: yes

#light:
#  - platform: group
#    name: Kitchen Lights
#    entities:
#      - light.6135078584f3eb0b3b30
#      - light.7808263084f3eb808d91